### PR TITLE
icon cleanup and select from current channels feature

### PR DESCRIPTION
**Pull request by ericbjones**
the workflow and keyword prompt in alfred had poop emojis.  fixed that.

### CODE REVIEW

**Comment by ericbjones** [comment]
this is really awesome stuff

**Comment by joech4n** [comment]
@ericbjones Any chance you could commit decompiled Applescript instead?

**Comment by ericbjones** [comment]
@joech4n , the AppleScript didn’t change. The overall workflow did. You’ll need to delete or rename your workflow in Alfred to reimport this one.

**Comment by ericbjones** [comment]
Or did you mean for the filter part?

**Comment by ericbjones** [comment]
Ah, I see. My bad.

**Comment by ericbjones** [comment]
@joech4n hows that?

**Review by joech4n — APPROVED** [review]

**Comment by joech4n** [comment]
Looks like it doesn't do fuzzy matching anymore.

Edit: Just noticed https://github.com/ericbjones/alfredchimeflows/issues/4

**Pull request merged**
